import {cp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
await rm(new URL('./dist/',import.meta.url),{recursive:true,force:true});
await mkdir('dist/server',{recursive:true});
await mkdir('dist/.openai',{recursive:true});
const paths=['index.html','styles.css','app.js','sw.js','manifest.webmanifest','icon.svg','src/domain.js','src/i18n.js','src/store.js','src/icons.js','src/islam-content.js'];
const assets={};
for(const path of paths)assets['/'+path]=await readFile(path,'utf8');
const binary={};
for(const path of ['icon-192.png','icon-512.png'])binary['/'+path]=(await readFile(path)).toString('base64');
const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
const domain=await readFile('src/domain.js','utf8');
const handler=(await readFile('src/api-worker.js','utf8')).replace("import { validate } from './domain.js';",'');
const worker=`${domain}\n${handler}\nconst assets=${JSON.stringify(assets)};\nconst binary=${JSON.stringify(binary)};\nconst types=${JSON.stringify(types)};\nexport default {async fetch(request,env){const p=new URL(request.url).pathname;if(p.startsWith('/api/')||p==='/health')return api(request,env);const key=p==='/'?'/index.html':p;const text=assets[key],encoded=binary[key];if(text===undefined&&encoded===undefined)return new Response('Not found',{status:404});const body=encoded===undefined?text:Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));return new Response(body,{headers:{'content-type':(types[key.slice(key.lastIndexOf('.'))]||'text/plain')+(encoded===undefined?'; charset=utf-8':''),'cache-control':'no-cache','x-content-type-options':'nosniff','referrer-policy':'same-origin','Content-Security-Policy':\"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; manifest-src 'self'; worker-src 'self'\"}})}};`;
await writeFile('dist/server/index.js',worker);
const hostingManifest=existsSync('.openai/hosting.json')?'.openai/hosting.json':'.openai/hosting.example.json';
await cp(hostingManifest,'dist/.openai/hosting.json');
await cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Built Worker with application assets and migrations.');
