import { FormEvent, ReactNode, useMemo, useState } from "react";
import { translate } from "../i18n";
import type { Note, Workspace } from "../types";

interface Props { workspace: Workspace; today: string; saving: boolean; onChange: (workspace: Workspace) => Promise<boolean> }

export function NotesView({ workspace, today, saving, onChange }: Props) {
  const t = (key: Parameters<typeof translate>[1]) => translate(workspace.settings.language, key);
  const [query, setQuery] = useState(""); const [archived, setArchived] = useState(false); const [editing, setEditing] = useState<Note | null>(null);
  const notes = useMemo(() => workspace.notes.filter((note) => Boolean(note.archived) === archived).filter((note) => `${note.title} ${note.body} ${note.folder || ""} ${note.tags || ""}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(b.pinned) - Number(a.pinned)), [archived, query, workspace.notes]);
  async function save(note: Note) { const next = structuredClone(workspace); const index = next.notes.findIndex((item) => item.id === note.id); const value = { ...note, id: note.id || crypto.randomUUID(), createdAt: note.createdAt || today, updatedAt: today }; if (index < 0) next.notes.push(value); else next.notes[index] = value; if (await onChange(next)) setEditing(null); }
  async function remove(id: string) { if (!window.confirm(`${t("delete")}: ${t("note")}?`)) return; const next = structuredClone(workspace); next.notes = next.notes.filter((note) => note.id !== id); if (await onChange(next)) setEditing(null); }
  return <><section className="page-heading"><div><p className="eyebrow">{t("notes").toUpperCase()}</p><h1>{t("notes")}</h1></div><button className="primary" onClick={() => setEditing({ id: "", title: "", body: "", color: "blue", pinned: false, archived: false })}>+ {t("add")}</button></section><div className="toolbar"><div className="segments"><button className={!archived ? "active" : ""} onClick={() => setArchived(false)}>{t("active")}</button><button className={archived ? "active" : ""} onClick={() => setArchived(true)}>{t("archived")}</button></div><input className="search-input" placeholder={t("search")} value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="notes-grid">{notes.map((note) => <button className={`card note-card ${note.color || "blue"}`} key={note.id} onClick={() => setEditing(structuredClone(note))}>{note.pinned && <span>{t("pinned")}</span>}<strong>{note.title}</strong><p>{note.body}</p><small>{[note.folder, note.tags].filter(Boolean).join(" · ") || "—"}</small></button>)}{!notes.length && <article className="card empty-state">{t("noResults")}</article>}</div>{editing && <NoteEditor note={editing} workspace={workspace} saving={saving} onClose={() => setEditing(null)} onSave={save} onDelete={editing.id ? remove : undefined} />}</>;
}

function NoteEditor({ note, workspace, saving, onClose, onSave, onDelete }: { note: Note; workspace: Workspace; saving: boolean; onClose: () => void; onSave: (note: Note) => void; onDelete?: (id: string) => void }) {
  const t = (key: Parameters<typeof translate>[1]) => translate(workspace.settings.language, key);
  const [value, setValue] = useState(note); const [preview, setPreview] = useState(false); const update = <K extends keyof Note>(key: K, next: Note[K]) => setValue((current) => ({ ...current, [key]: next }));
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...value, title: value.title.trim() }); };
  return <div className="modal-backdrop"><section className="modal note-modal"><header><h2>{note.id ? `${t("edit")} · ${t("note")}` : `${t("add")} · ${t("note")}`}</h2><button onClick={onClose}>×</button></header><form onSubmit={submit}><label className="full">{t("title")}<input required autoFocus value={value.title} onChange={(e) => update("title", e.target.value)} /></label><label className="full">{t("body")}<textarea className="note-body" value={value.body} onChange={(e) => update("body", e.target.value)} /></label>{preview && <div className="markdown-preview full"><SafeMarkdown text={value.body} /></div>}<label>{t("folder")}<input value={value.folder || ""} onChange={(e) => update("folder", e.target.value)} /></label><label>{t("tags")}<input value={value.tags || ""} onChange={(e) => update("tags", e.target.value)} /></label><label>{t("color")}<select value={value.color || "blue"} onChange={(e) => update("color", e.target.value as Note["color"])}>{(["blue", "violet", "rose", "green"] as const).map((color) => <option key={color} value={color}>{t(color)}</option>)}</select></label><label>{t("project")}<select value={value.projectId || ""} onChange={(e) => update("projectId", e.target.value)}><option value="">{t("none")}</option>{workspace.projects.map((project) => <option value={project.id} key={project.id}>{project.title}</option>)}</select></label><label className="toggle"><input type="checkbox" checked={Boolean(value.pinned)} onChange={(e) => update("pinned", e.target.checked)} />{t("pinned")}</label><label className="toggle"><input type="checkbox" checked={Boolean(value.archived)} onChange={(e) => update("archived", e.target.checked)} />{t("archived")}</label><footer>{onDelete && <button className="danger" type="button" onClick={() => onDelete(note.id)}>{t("delete")}</button>}<button type="button" onClick={() => setPreview((current) => !current)}>{t("preview")}</button><span /><button type="button" onClick={onClose}>{t("cancel")}</button><button className="primary" disabled={saving}>{t("save")}</button></footer></form></section></div>;
}

function SafeMarkdown({ text }: { text: string }) {
  const nodes: ReactNode[] = text.split("\n").map((line, index) => { if (line.startsWith("### ")) return <h3 key={index}>{line.slice(4)}</h3>; if (line.startsWith("## ")) return <h2 key={index}>{line.slice(3)}</h2>; if (line.startsWith("# ")) return <h1 key={index}>{line.slice(2)}</h1>; if (/^[-*] /.test(line)) return <li key={index}>{line.slice(2)}</li>; return <p key={index}>{line || " "}</p>; });
  return <>{nodes}</>;
}
