import { FormEvent, useState } from "react";
import { shiftDate, weekDates } from "../domain/calendar";
import { habitIsDue } from "../domain/habits";
import { translate } from "../i18n";
import type { Review, Workspace } from "../types";

interface Props { workspace: Workspace; today: string; saving: boolean; onChange: (workspace: Workspace) => Promise<boolean> }
export function ReviewView({ workspace, today, saving, onChange }: Props) {
  const t = (key: Parameters<typeof translate>[1]) => translate(workspace.settings.language, key);
  const [anchor, setAnchor] = useState(today); const dates = weekDates(anchor, workspace.settings.weekStart); const start = dates[0]; const end = dates[6]; const existing = workspace.reviews.find((review) => review.week === start); const [value, setValue] = useState<Review>(existing || { id: "", week: start });
  const counts = dates.map((date) => workspace.tasks.filter((task) => task.completedAt === date && task.status === "completed").length); const max = Math.max(1, ...counts); let due = 0; let checked = 0; for (const habit of workspace.habits) for (const date of dates.filter((item) => item <= today)) if (habitIsDue(habit, date)) { due += 1; if (habit.completions.includes(date)) checked += 1; }
  const changeWeek = (amount: number) => { const next = shiftDate(anchor, amount); const nextStart = weekDates(next, workspace.settings.weekStart)[0]; const review = workspace.reviews.find((item) => item.week === nextStart); setAnchor(next); setValue(review || { id: "", week: nextStart }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const next = structuredClone(workspace); const index = next.reviews.findIndex((review) => review.week === start); const review = { ...value, id: value.id || crypto.randomUUID(), week: start, createdAt: value.createdAt || today, updatedAt: today }; if (index < 0) next.reviews.push(review); else next.reviews[index] = review; await onChange(next); };
  return <><section className="page-heading"><div><p className="eyebrow">{t("reflection").toUpperCase()}</p><h1>{t("review")}</h1></div><div className="review-nav"><button onClick={() => changeWeek(-7)}>←</button><span>{start} — {end}</span><button onClick={() => changeWeek(7)}>→</button></div></section><div className="finance-summary"><article className="card"><small>{t("completed")} · {t("tasks")}</small><strong>{counts.reduce((sum, count) => sum + count, 0)}</strong></article><article className="card"><small>{t("habits")}</small><strong>{due ? Math.round(checked / due * 100) : 0}%</strong></article><article className="card"><small>{t("notes")}</small><strong>{workspace.notes.filter((note) => note.createdAt && note.createdAt >= start && note.createdAt <= end).length}</strong></article></div><div className="review-layout"><article className="card"><h2>{t("weeklyProgress")}</h2><div className="review-chart">{counts.map((count, index) => <div key={dates[index]}><small>{count}</small><i style={{ height: `${Math.max(3, count / max * 130)}px` }} /><span>{new Intl.DateTimeFormat(workspace.settings.language, { weekday: "short", timeZone: "UTC" }).format(new Date(`${dates[index]}T12:00:00Z`))}</span></div>)}</div></article><article className="card"><h2>{t("reflection")}</h2><form className="reflection" onSubmit={submit}><label>{t("wins")}<textarea value={value.wins || ""} onChange={(e) => setValue({ ...value, wins: e.target.value })} /></label><label>{t("improve")}<textarea value={value.improve || ""} onChange={(e) => setValue({ ...value, improve: e.target.value })} /></label><label>{t("nextFocus")}<textarea value={value.nextFocus || ""} onChange={(e) => setValue({ ...value, nextFocus: e.target.value })} /></label><button className="primary" disabled={saving}>{t("save")}</button></form></article></div></>;
}
