import { ChangeEvent, FormEvent, useRef, useState } from "react";
import type { Workspace } from "../types";

interface Props { workspace: Workspace; saving: boolean; onChange: (workspace: Workspace) => Promise<boolean> }
export function SettingsView({ workspace, saving, onChange }: Props) {
  const [settings, setSettings] = useState(workspace.settings); const [error, setError] = useState(""); const file = useRef<HTMLInputElement>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); await onChange({ ...structuredClone(workspace), settings }); };
  const exportData = () => { const blob = new Blob([JSON.stringify(workspace, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `n-os-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const importData = async (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (!selected) return; try { if (selected.size > 1_500_000) throw new Error(); const value = JSON.parse(await selected.text()) as Workspace; if (value.schema !== 3 || !value.settings || !Array.isArray(value.tasks)) throw new Error(); if (!window.confirm("Импорт полностью заменит текущее пространство. Продолжить?")) return; await onChange(value); setError(""); } catch { setError("Файл повреждён или имеет неподдерживаемый формат."); } finally { event.target.value = ""; } };
  return <><section className="page-heading"><div><p className="eyebrow">ПЕРСОНАЛИЗАЦИЯ</p><h1>Настройки</h1></div></section><div className="settings-layout"><article className="card"><h2>Рабочее пространство</h2><form className="settings-form" onSubmit={submit}><label>Имя<input value={settings.name} onChange={(e) => setSettings({ ...settings, name: e.target.value })} /></label><label>Язык<select value={settings.language} onChange={(e) => setSettings({ ...settings, language: e.target.value as "ru" | "en" })}><option value="ru">Русский</option><option value="en">English</option></select></label><label>Тема<select value={settings.theme} onChange={(e) => setSettings({ ...settings, theme: e.target.value as "light" | "dark" | "system" })}><option value="system">Системная</option><option value="dark">Тёмная</option><option value="light">Светлая</option></select></label><label>Часовой пояс<input required value={settings.timezone} onChange={(e) => setSettings({ ...settings, timezone: e.target.value })} /></label><label>Основная валюта<select value={settings.currency} onChange={(e) => setSettings({ ...settings, currency: e.target.value })}>{["TJS", "USD", "EUR", "RUB", "CNY"].map((currency) => <option key={currency}>{currency}</option>)}</select></label><label>Начало недели<select value={settings.weekStart} onChange={(e) => setSettings({ ...settings, weekStart: Number(e.target.value) })}><option value="1">Понедельник</option><option value="0">Воскресенье</option></select></label><label className="toggle"><input type="checkbox" checked={settings.reducedTransparency} onChange={(e) => setSettings({ ...settings, reducedTransparency: e.target.checked })} />Уменьшить прозрачность</label><button className="primary" disabled={saving}>Сохранить</button></form></article><article className="card data-card"><h2>Данные</h2><p>Экспорт создаёт локальную резервную копию. Перед импортом обязательно сохраните текущие данные.</p><button onClick={exportData}>Экспорт JSON</button><button className="danger" onClick={() => { exportData(); file.current?.click(); }}>Экспортировать и импортировать</button><input ref={file} hidden type="file" accept=".json,application/json" onChange={importData} />{error && <p className="form-error">{error}</p>}</article></div></>;
}
