import { useEffect, useMemo, useState } from "react";
import { eventOccurs } from "../domain/calendar";
import { translate } from "../i18n";
import type { Workspace } from "../types";

interface InstallPromptEvent extends Event { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> }
interface Props { workspace: Workspace; today: string; onNavigate: (view: string) => void }

export function ShellTools({ workspace, today, onNavigate }: Props) {
  const [panel, setPanel] = useState<"search" | "notifications" | null>(null); const [query, setQuery] = useState(""); const [install, setInstall] = useState<InstallPromptEvent | null>(null);
  useEffect(() => { const capture = (event: Event) => { event.preventDefault(); setInstall(event as InstallPromptEvent); }; window.addEventListener("beforeinstallprompt", capture); return () => window.removeEventListener("beforeinstallprompt", capture); }, []);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPanel("search"); } }; window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, []);
  const results = useMemo(() => { const text = query.trim().toLowerCase(); const collections = [{ view: "tasks", rows: workspace.tasks }, { view: "calendar", rows: workspace.events }, { view: "habits", rows: workspace.habits }, { view: "notes", rows: workspace.notes }, { view: "goals", rows: workspace.goals }, { view: "projects", rows: workspace.projects }, { view: "finance", rows: workspace.accounts }]; return collections.flatMap(({ view, rows }) => rows.map((row) => ({ view, id: row.id, title: row.title, text: `${row.title} ${"description" in row ? row.description || "" : ""} ${"body" in row ? row.body : ""}` }))).filter((item) => !text || item.text.toLowerCase().includes(text)).slice(0, 30); }, [query, workspace]);
  const notifications = [...workspace.tasks.filter((task) => task.date && task.date <= today && !["completed", "cancelled"].includes(task.status)).map((task) => ({ view: "tasks", title: task.title, detail: task.date === today ? "Сегодня" : `Просрочено · ${task.date}` })), ...workspace.events.filter((event) => Number(event.reminder) > 0 && eventOccurs(event, today)).map((event) => ({ view: "calendar", title: event.title, detail: `${event.time} · за ${event.reminder} мин` }))];
  const navigate = (view: string) => { onNavigate(view); setPanel(null); setQuery(""); };
  const installApp = async () => { if (!install) return; await install.prompt(); await install.userChoice; setInstall(null); };
  const t = (key: Parameters<typeof translate>[1]) => translate(workspace.settings.language, key);
  return <><div className="shell-tools"><button onClick={() => setPanel("search")}>{t("search")} <kbd>⌘K</kbd></button><button className="notification-button" onClick={() => setPanel("notifications")}>{t("notifications")}{notifications.length > 0 && <b>{notifications.length}</b>}</button>{install && <button onClick={installApp}>{t("installApp")}</button>}</div>{panel && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setPanel(null)}><section className="modal shell-panel"><header><h2>{panel === "search" ? t("search") : t("notifications")}</h2><button onClick={() => setPanel(null)}>×</button></header>{panel === "search" ? <div className="panel-body"><input autoFocus className="global-search" placeholder={t("search")} value={query} onChange={(event) => setQuery(event.target.value)} /><div className="search-results">{results.map((item) => <button key={`${item.view}-${item.id}`} onClick={() => navigate(item.view)}><strong>{item.title}</strong><small>{item.view}</small></button>)}{!results.length && <p className="muted">{t("noResults")}</p>}</div></div> : <div className="panel-body search-results">{notifications.map((item, index) => <button key={`${item.view}-${index}`} onClick={() => navigate(item.view)}><strong>{item.title}</strong><small>{item.detail}</small></button>)}{!notifications.length && <p className="muted">{t("noReminders")}</p>}</div>}</section></div>}</>;
}
